language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/users

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  users;' -U postgres
  - psql -U postgres -d users -a -f tables.sql

services:
  - postgresql